# Generated by Django 4.1.7 on 2023-02-19 11:38

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_location_state_location_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=localflavor.us.models.USStateField(default='None', max_length=2),
        ),
    ]
