# Generated by Django 4.1.7 on 2023-02-20 14:24

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(default=123123, max_length=10),
            preserve_default=False,
        ),
    ]
