# Generated by Django 4.1.7 on 2023-02-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_location_address_1_alter_location_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
