# Generated by Django 4.1.7 on 2023-02-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
    ]
