# Generated by Django 4.1.7 on 2023-02-24 09:48

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.png', null=True, upload_to=users.utils.user_directory_path),
        ),
    ]
