# Generated by Django 4.1.7 on 2023-02-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='transmisson',
            new_name='transmission',
        ),
    ]
